spring:
  datasource:
    druid:
      username: root
      password: 123456789
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: mapper/*xml
  type-aliases-package: com.atguigu.blog.pojo

logging:
  level:
    root: warn
    com.atguigu: info
  file:
    path: log/log.log

server:
  port: 8081